name: Check for new forks
on:
  schedule:
    # Runs at 08:00 UTC every day.
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17.x"
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Check for new forks
        id: check
        run: |
          go run cmd/forks/main.go check 2> errors.txt || true
          echo ::set-output name=errors::`cat errors.txt`
          go run cmd/forks/main.go check
      - name: Slack Notification
        if: ${{ always() && steps.check.outputs.errors != 'success' }}
        uses: rtCamp/action-slack-notify@12e36fc18b0689399306c2e0b3e0f2978b7f1ee7
        env:
          SLACK_USERNAME: GitHub Action as a Service
          SLACK_COLOR: 'red'
          SLACK_TITLE: 'Message'
          SLACK_CHANNEL: 'checks'
          SLACK_MESSAGE: ${{ steps.check.outputs.errors }}
          SLACK_ICON_EMOJI: ':this-is-fine:'
          SLACK_FOOTER: "Periodic forks check failed :ahhhhhhhhh:"
          SLACK_WEBHOOK: ${{ secrets.SLACK_PRIV_WEBHOOK }}
